### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by edif2008** [1Password/connect-sdk-js#55]
## Summary

Currently this is what the users can do when it comes to vaults:
- `listVaults` - get the list of all vaults that the Connect token has access to.
- `getVault(vaultId)` - get a Vault by its ID.

We want to enhance the way users can get vaults when using the Connect Node SDK. In this issue, we want to enable users to get a vault by its title.

## Tasks to be done

You can divide this work into smaller PRs to make the review process smoother. One way of achieving this is add a function along with its tests and open a PR with the new function.

- [ ] Implement `getVaultByTitle` function in the `Vaults` class in `src/lib/resources.ts`:
   ```ts
   /**
    * Searches for a Vault with a case-sensitive, exact match on title.
    * If found, queries for complete vault details and returns result.
    *
    * @param {string} title
    * @returns {Promise<Vault>}
    * @private
    */
   private async getVaultByTitle(
            vaultId: string,
            title: string,
        ): Promise<Response> {
        // functionality
   }
   ```
- [ ] Implement `getVaultByTitle` function in OPConnect class in `src/lib/op-connect.ts`:
  ```ts
  /**
     * Get details about a specific vault with a matching Title value.
     *
     * The Vault Title is case-sensitive and must be an exact-match.
     *
     * @param {string} vaultTitle
     * @returns {Promise<Vault>}
     */
    public async getVault(vaultTitle: string): Promise<Vault> {
        return await this.vaults.getVaultByTitle(vaultTitle);
    }
  ```
- [ ] Add a test for the new function in `__test__/op-connect.test.ts` below `get vault` test case:
  ```ts
  test("get vault by titte", async () => {
      // actual test here
  }
  ```

**Comment by edif2008** [comment]
This issue is currently blocked by #56
