### ISSUE TITLE
Add functionality to get multiple vaults by a title

### ISSUE THREAD

**Issue by edif2008** [1Password/connect-sdk-js#56]
## Summary

Currently this is what the users can do when it comes to vaults:
- `listVaults` - get the list of all vaults that the Connect token has access to.
- `getVault(vaultId)` - get a Vault by its ID.

We want to enhance the way users can get vaults when using the Connect Node SDK. In this issue, we want to enable users to get a list of vaults that have the given title.

## Tasks to be done

- [x] Implement `getVaultsByTitle` function in the `Vaults` class in `src/lib/resources.ts`:
   ```ts
   /**
    * Search for all Vaults with an exact match on title.
    *
    * @param {string} title
    * @returns {Promise<Vault[]>}
    * @private
    */
   private async listVaultsByTitle(
            title: string,
        ): Promise<Response> {
        // functionality
   }
   ```
- [x] Implement `listVaultsByTitle` function in OPConnect class in `src/lib/op-connect.ts`:
  ```ts
  /**
   * Returns a list of Vaults with a matching Title value.
   *
   * The Vault Title is case-sensitive and must be an exact-match.
   *
   * @param {string} vaultTitle
   * @returns {Promise<Vault[]>}
   */
  public async listVaultsByTitle(vaultTitle: string): Promise<Vault[]> {
        return await this.vaults.getVaultsByTitle(vaultTitle);
  }
  ```
- [x] Add a test for the new function in `__test__/op-connect.test.ts` below `get vault` test case:
  ```ts
  test("list vaults by titte", async () => {
      // actual test here
  }
  ```
