### ISSUE TITLE
Enhance `getVault` functionality

### ISSUE THREAD

**Issue by edif2008** [1Password/connect-sdk-js#57]
## Sumary

We want users to have an easy flow when using this SDK. For vaults, we want them to be able to provide either the ID or the title as a parameter.

## Tasks to be done

- [x] Rename `getVault` to `getVaultById` in `src/lib/resources.ts`
- [x] Create the new `getVault` function in `src/lib/resources.ts` that expects either the Vault name or its ID. The important part of this functionality is to check if the provided string is a valid ID or not (i.e. it matches the following regex: `"^[a-z0-9]{26}$"`). You can use as an inspiration the [`get` function for the Item class](https://github.com/1Password/connect-sdk-js/blob/09bddd7f919373a5f5a8130ab332de5bc6024d1c/src/lib/resources.ts#L86-L96). 
- [x] Adjust `getVault` by changing the parameter name to suggest that either the name or ID is accepted (e.g. `vaultQuery`).
- [x] Create a new function `getValutById` in `src/lib/op-connect.ts`
  ```ts
  /**
   * Get details about a specific vault with a matching ID value.
   *
   * @param {string} vaultId
   * @returns {Promise<Vault>}
   */
  public async getVaultById(vaultId: string): Promise<Vault> {
      return await this.vaults.getVaultById(vaultId);
  }
  ```
- [x] Add and adjust tests for the new functions in `__test__/op-connect.test.ts`

**Comment by edif2008** [comment]
This issue is blocked by #56 and #55
