### ISSUE TITLE
Add functionality to get multiple items by a title

### ISSUE THREAD

**Issue by edif2008** [1Password/connect-sdk-js#58]
## Summary

We want to enhance the way users can get items when using the Connect Node SDK. In this issue, we want to enable users to get a list of items that have the given title.

## Tasks to be done

- [x] Implement `listItemsByTitle` function in the `Items` class in `src/lib/resources.ts`. Important note: The API response returns an Item summary, not the full item, therefore once you get the list of item summaries, for each item you have to call `getItemById`.
   ```ts
   /**
    * Search for all Items with an exact match on title.
    *
    * @param {string} title
    * @returns {Promise<FullItem[]>}
    * @private
    */
   private async listItemssByTitle(
            vaultId: string,
            title: string,
        ): Promise<Response> {
        // functionality
   }
   ```
   Tip: You can move [this snippet](https://github.com/1Password/connect-sdk-js/blob/09bddd7f919373a5f5a8130ab332de5bc6024d1c/src/lib/resources.ts#L125-L136) from `get` to `listItemsByTitle` and then call `listItemsByTitle` in `get`. In this way, you avoid duplicate code in the two function.
- [x] Implement `listItemsByTitle` function in OPConnect class in `src/lib/op-connect.ts`:
  ```ts
  /**
   * Returns a list of Items with a matching Title value.
   *
   * @param {string} vaultId
   * @param {string} itemTitle
   * @returns {Promise<FullItem[]>}
   */
  public async listItemsByTitle(vaultId: string, itemTitle: string): Promise<FullItem[]> {
        return await this.items.listItemsByTitle(vaultId, itemTitle);
  }
  ```
- [x] Add a test for the new function in `__test__/op-connect.test.ts` below `get item` test case:
  ```ts
  test("list items by titte", async () => {
      // actual test here
  }
  ```
