### ISSUE TITLE
Enhance `getItem` functionality

### ISSUE THREAD

**Issue by edif2008** [1Password/connect-sdk-js#59]
## Sumary

We want users to have an easy flow when using this SDK. For items, we want them to be able to provide either the ID or the title of an item as a parameter.

## Tasks to be done

- [x] Adjust `get` function in `src/lib/resources.ts` so that now it checks whether the input is a valid Item ID or not (i.e. it matches the following regex: `"^[a-z0-9]{26}$"`)
- [x] Adjust `getItem` by changing the parameter name to suggest that either the name or ID is accepted (e.g. `itemQuery`).
- [x] Create a new function `getItemById` in `src/lib/op-connect.ts`
  ```ts
  /**
   * Get details about a specific vault with a matching ID value.
   *
   * @param {string} vaultId
   * @param {string} itemId
   * @returns {Promise<FullItem>}
   */
  public async getItemById(vaultId: string, itemId: string): Promise<FullItem> {
      return await this.items.getById(vaultId, itemId);
  }
  ```
- [x] Add and adjust tests for the new functions in `__test__/op-connect.test.ts`

**Comment by edif2008** [comment]
This issue is blocked by #58
