### ISSUE TITLE
Add functionality to delete Item by title

### ISSUE THREAD

**Issue by edif2008** [1Password/connect-sdk-js#60]
## Summary

We want to enhance the way users can delete items when using the Connect Node SDK. In this issue, we want to enable users to delete an item that has the given title.

## Tasks to be done

- [x] Implement `deleteByTitle` function in the `Items` class in `src/lib/resources.ts`:
   ```ts
   /**
    * Deletes an item with a case-sensitive, exact match on title.
    *
    * @param {string} vaultId
    * @param {string} title
    * @returns {Promise<void>}
    * @private
    */
   private async deleteItemByTitle(
            vaultId: string,
            title: string,
        ): Promise<Response> {
        // functionality
   }
   ```
- [x] Implement `deleteItemByTitle` function in OPConnect class in `src/lib/op-connect.ts`:
  ```ts
  /**
   * Delete a specific item with a matching Title value.
   *
   * The Item Title is case-sensitive and must be an exact-match.
   *
   * @param {string} vaultId
   * @param {string} itemTitle
   * @returns {Promise<void>}
   */
  public async deleteItemByTitle(vaultId: string, itemTitle: string): Promise<void> {
        return await this.items.deleteByTitle(vaultId, itemTitle);
  }
  ```
- [x] Add a test for the new function in `__test__/op-connect.test.ts` below `delete item` test case:
  ```ts
  test("delete item by titte", async () => {
      // actual test here
  }
  ```
