### ISSUE TITLE
Enhance `deleteItem` functionality

### ISSUE THREAD

**Issue by edif2008** [1Password/connect-sdk-js#61]
## Sumary

We want users to have an easy flow when using this SDK. For items, we want them to be able to provide either the ID or the title of an item as a parameter. In this issue, we will address this for deleting items.

## Tasks to be done

- [x] Rename `delete` function in `src/lib/resources.ts` to `deleteById`
- [x] Create the new `delete` function in `src/lib/resources.ts` that expects either the Item name or its ID. The important part of this functionality is to check if the provided string is a valid ID or not (i.e. it matches the following regex: `"^[a-z0-9]{26}$"`)
- [x] Adjust `deleteItem` by changing the parameter name to suggest that either the name or ID is accepted (e.g. `itemQuery`).
- [x] Create a new function `deleteItemById` in `src/lib/op-connect.ts`
  ```ts
  /**
   * Delete a specific item with a matching ID value.
   *
   * @param {string} vaultId
   * @param {string} itemId
   * @returns {Promise<void>}
   */
  public async deleteItemById(vaultId: string, itemId: string): Promise<void> {
      return await this.items.deleteById(vaultId, itemId);
  }
  ```
- [x] Add and adjust tests for the new functions in `__test__/op-connect.test.ts`

**Comment by edif2008** [comment]
This issue is blocked by #60
