### ISSUE TITLE
Add functionality to get File by ID

### ISSUE THREAD

**Issue by edif2008** [1Password/connect-sdk-js#63]
## Summary

Starting with Connect 1.3.0, the users can get files that are stored in an Item. Connect Node SDK should enable the users to do that.

In this issue, we will get a file based on its ID.

## Tasks to be done

- [ ] Implement `getFileById` function in the `Items` class in `src/lib/resources.ts`. The API endpoint that this function needs to call is `v1/vaults/vaultId/items/itemId/files/fileId`.
   ```ts
   /**
    * Get an Item's specific File with a matching ID value.
    *
    * @param {string} vaultId
    * @param {string} itemQuery
    * @param {string} fileId
    * @returns {Promise<ItemFile>}
    * @private
    */
   private async getFileById(
            vaultId: string,
            itemQuery: string,
            fileId: string,
        ): Promise<ItemFile> {
        // functionality
   }
   ```
   Note: Feel free to place this functionality in a separate class (e.g. Files) if you feel it's more suitable. This is just a suggested approach.
- [ ] Implement `getFileById` function in OPConnect class in `src/lib/op-connect.ts`:
  ```ts
  /**
   * Get an Item's specific File with a matching ID value.
   *
   * @param {string} vaultId
   * @param {string} itemQuery
   * @param {string} fileId
   * @returns {Promise<ItemFile>}
   */
  public async getFileById(vaultId: string, itemQuery: string, fileId: string): Promise<ItemFile> {
        return await this.items.getFileByID(vaultId, itemQuery);
  }
  ```
- [ ] Add a test for the new function in `__test__/op-connect.test.ts`:
  ```ts
  test("get file", async () => {
      // actual test here
  }
  ```

**Comment by edif2008** [comment]
This issue is blocked by #62
