### ISSUE TITLE
Add functionality to get a File's content

### ISSUE THREAD

**Issue by edif2008** [1Password/connect-sdk-js#64]
## Summary

Starting with Connect 1.3.0, the users can get files that are stored in an Item. Connect Node SDK should enable the users to do that.

In this issue, we will get a file's content.

## Tasks to be done

- [ ] Implement `getFileContent` function in the `Items` class in `src/lib/resources.ts`. The API endpoint that this function needs to call is `v1/vaults/vaultId/items/itemId/files/fileId/content`. You'll have to figure out the object type the promise expects.
   ```ts
   /**
    * Get an Item File's content.
    *
    * @param {string} vaultId
    * @param {string} itemQuery
    * @param {string} fileId
    * @returns {Promise<>}
    * @private
    */
   private async getFileContent(
            vaultId: string,
            itemQuery: string,
            fileId: string,
        ): Promise<> {
        // functionality
   }
   ```
   Note: Feel free to place this functionality in a separate class (e.g. Files) if you feel it's more suitable. This is just a suggested approach. 
- [ ] Implement `getFileContent` function in OPConnect class in `src/lib/op-connect.ts`:
  ```ts
  /**
   * Get an Item File's content.
   *
   * @param {string} vaultId
   * @param {string} itemQuery
   * @param {string} fileId
   * @returns {Promise<>}
   */
  public async getFileContent(vaultId: string, itemQuery: string, fileId: string): Promise<> {
        return await this.items.getFileContent(vaultId, itemQuery);
  }
  ```
- [ ] Add a test for the new function in `__test__/op-connect.test.ts`:
  ```ts
  test("get file content", async () => {
      // actual test here
  }
  ```

**Comment by edif2008** [comment]
This issue is blocked by #62
